# Real pima indians diabetes
## Setup

In [164]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

## Make sure we get the same value

This is because we're using a stochastic model, it means we"ll get the same answer every time because we're essentially disabling randomness for a little bit.

In [165]:
seed = 7
np.random.seed(seed)

## Lets have a sneaky peak at that data

In [166]:
df = pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148           72.0             35    169.5  33.6   
1              1       85           66.0             29    102.5  26.6   
2              8      183           64.0             32    169.5  23.3   
3              1       89           66.0             23     94.0  28.1   
4              0      137           40.0             35    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101           76.0             48    180.0  32.9   
764            2      122           70.0             27    102.5  36.8   
765            5      121           72.0             23    112.0  26.2   
766            1      126           60.0             32    169.5  30.1   
767            1       93           70.0             31    102.5  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [167]:
x = df.iloc[:, 0:8].to_numpy()
y = df.iloc[:, 8].to_numpy()
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [168]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

Here's we're reserving ⅓ of the data for testing, so we don't over-fit.

In [169]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.33, random_state=seed)

## Now the keras stuff

In [170]:
model = tf.keras.Sequential()
model.add(
    tf.keras.layers.Dense(
        12,
        kernel_initializer=tf.keras.initializers.random_uniform,
        activation=tf.keras.activations.relu
    )
)
model.add(
    tf.keras.layers.Dense(
        8,
        kernel_initializer=tf.keras.initializers.random_uniform,
        activation=tf.keras.activations.relu
    )
)
model.add(
    tf.keras.layers.Dense(
        8,
        kernel_initializer=tf.keras.initializers.random_uniform,
        activation=tf.keras.activations.relu
    )
)
model.add(
    tf.keras.layers.Dense(
        1,
        kernel_initializer=tf.keras.initializers.random_uniform,
        activation=tf.keras.activations.sigmoid
    )
)

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=[tf.keras.metrics.binary_accuracy]
)

## Fitting

This takes a little while. Maybe I have too many epochs?

In [171]:
model.fit(train_x, train_y, epochs=500, batch_size=10)

Epoch 1/500
52/52 [==============================] - 1s 1ms/step - loss: 0.6870 - binary_accuracy: 0.6518
Epoch 2/500
52/52 [==============================] - 0s 2ms/step - loss: 0.6644 - binary_accuracy: 0.6576
Epoch 3/500
52/52 [==============================] - 0s 2ms/step - loss: 0.6453 - binary_accuracy: 0.6576
Epoch 4/500
52/52 [==============================] - 0s 2ms/step - loss: 0.6078 - binary_accuracy: 0.6576
Epoch 5/500
52/52 [==============================] - 0s 2ms/step - loss: 0.5506 - binary_accuracy: 0.6887
Epoch 6/500
52/52 [==============================] - 0s 2ms/step - loss: 0.5072 - binary_accuracy: 0.7821
Epoch 7/500
52/52 [==============================] - 0s 2ms/step - loss: 0.4874 - binary_accuracy: 0.7879
Epoch 8/500
52/52 [==============================] - 0s 2ms/step - loss: 0.4826 - binary_accuracy: 0.7860
Epoch 9/500
52/52 [==============================] - 0s 2ms/step - loss: 0.4725 - binary_accuracy: 0.8035
Epoch 10/500
52/52 [==========================

## Now we see how well it worked

In [172]:
scores = model.evaluate(test_x, test_y)
scores

8/8 [==============================] - 0s 2ms/step - loss: 0.4470 - binary_accuracy: 0.8504


[0.44704893231391907, 0.8503937125205994]

Hmm, that's not super helpful

In [173]:
print(f"{model.metrics_names[0]}: {scores[0] * 100}")
print(f"{model.metrics_names[1]}: {scores[1] * 100}%")

loss: 44.70489323139191
binary_accuracy: 85.03937125205994%


## Lets use it!

In [174]:
preds = model.predict(
    pd.DataFrame(
        [{
            "Pregnancies": 6, "Glucose": 148, "BloodPressure": 72, "SkinThickness": 35,
            "Insulin": 169.5, "BMI": 33.6, "DiabetesPedigreeFunction": 0.627,
            'Age': 50
        }]
    ).to_numpy()
)

preds

array([[0.98651356]], dtype=float32)